#!/usr/bin/env bash
#vim: tw=0 ai

function gcs_to_bq_temp() {
    datasource="$1"
    country="gbr"
    datefmt="202302"
    bucket="carto-ext-prov-echo-analytics"
    bucket_trim=$(echo ${bucket} | tr '-' '_')
    bq_dataset="data-observatory-ops:do_raw"

    from_gcs="gs://${bucket}/${datasource}/${gbr}/${datefmt}*.parquet"
    to_bq_table="${bq_dataset}.${bucket_trim}_${gbr}_${datasource}_${datefmt}_parquet"

    bq load --replace --source_format PARQUET ${to_bq_table} ${from_gcs}

    echo Loaded
    echo ${to}
}

function schema_from_sheet() {
    sheet_url="$1"
    fmt=".loc[:, ['column_name', 'db_type']].rename({'column_name': 'name', 'db_type': 'type'}, axis=1).to_json(orient='records')"
    out_file="/tmp/gs_schema_$(uuidgen).json"
    gsheet $sheet_url --fmt=$fmt > /tmp/raw_gs_schema.json
    cat /tmp/raw_gs_schema.json | tr -d '\n' | python3 -m json.tool > $out_file
    echo $out_file
}

function schema_from_bq() {
    out_file="/tmp/bq_schema_$(uuidgen).json"
    bq_table="$1"
    bq show --schema "${bq_table}" > /tmp/raw_bq_schema.json
    cat /tmp/raw_bq_schema.json | python3 -m json.tool | sed '/"mode":/d' | sed 's/\(\s\+"type":.*\),$/\1/g' > $out_file
    echo $out_file

}

function schema_diff() {
    editor=$EDITOR
    sch_bq=$(schema_from_bq "$1")
    sch_sheet=$(schema_from_sheet "$2")
    echo $sch_sheet
    echo $sch_bq
    $editor -d $sch_sheet $sch_bq +'nmap gq :qa!<cr>'
}
