#!/usr/bin/env bash
source $DOTFILES/shell/variables
source $DOTFILES/shell/customization
source $DOTFILES/shell/functions
source $DOTFILES/shell/aliases

[ ! -f ~/.bashrc ] && dotfilesLink

# bin
addToPath "/usr/local/bin"
addToPath "$HOME/bin"
addToPath "$HOME/.cargo/bin"
addToPath "$HOME/.local/bin"
addToPath "$HOME/.deno/bin"

# go
addToPathFront "$HOME/go/bin"
addToPathFront "/home/mgreco/.go/bin"
addToPathFront "/usr/local/go/bin"

# db
addToPathFront "/opt/mssql-tools/bin"
addToPath "/opt/mssql-tools/bin"

# ruby
addToPathFront "$GEM_HOME/bin"

# projects folders
addToMyGitProjects $HOME/github
addToMyGitProjects $HOME/gitlab



# nnn config
export NNN_FIFO=/tmp/nnn.fifo
# export NNN_OPENER=nuke
export NNN_PLUG='f:finder;o:fzopen;p:mocq;d:diffs;t:nmount;v:imgview'
alias lsn='nnn -de'

nnn_cd()
{
    if ! [ -z "$NNN_PIPE" ]; then
        printf "%s\0" "0c${PWD}" > "${NNN_PIPE}" !&
    fi
}

trap nnn_cd EXIT
