#!/usr/bin/env bash
# fast keyboard delay (ms) and speed (keys by sec)
# keyboard typing speed
[ -x "$(command -v xset)" ] && xset r rate 250 60
[ -x "$(command -v setxkbmap)" ] && setxkbmap -rules evdev -model evdev -layout us -variant altgr-intl
