#!/bin/bash
$include /etc/inputrc

set completion-ignore-case On

# Trying to make alt key send by xterm works with tmux
# https://vim.fandom.com/wiki/Get_Alt_key_to_work_in_terminal
# set meta-flag on
# set input-meta on
# set convert-meta on
# set output-meta on

# "\e[1~": beginning-of-line
# "\e[4~": end-of-line
