#!/usr/bin/env bash
# ================ COLORS
export LS_COLORS='di=1:fi=0:ln=31:pi=5:so=5:bd=5:cd=5:or=31:mi=0:ex=35:*.rb=90'
# Setup some colors to use later in interactive shell or scripts
export COLOR_NC='\e[0m' # No Color
export COLOR_WHITE='\e[1;37m'
export COLOR_BLACK='\e[0;30m'
export COLOR_BLUE='\e[0;34m'
export COLOR_LIGHT_BLUE='\e[1;34m'
export COLOR_GREEN='\e[0;32m'
export COLOR_LIGHT_GREEN='\e[1;32m'
export COLOR_CYAN='\e[0;36m'
export COLOR_LIGHT_CYAN='\e[1;36m'
export COLOR_RED='\e[0;31m'
export COLOR_LIGHT_RED='\e[1;32m'
export COLOR_PURPLE='\e[0;35m'
export COLOR_LIGHT_PURPLE='\e[1;35m'
export COLOR_BROWN='\e[0;33m'
export COLOR_YELLOW='\e[1;33m'
export COLOR_GRAY='\e[1;30m'
export COLOR_LIGHT_GRAY='\e[0;37m'

# ================ OPTIONS
# https://superuser.com/questions/71588/how-to-syntax-highlight-via-less
# export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
export LESS=' -R '
export SSH_KEY_PATH="~/.ssh/rsa_id"
export EDITOR="/usr/bin/nvim"

export AUTOENV_ENV_FILENAME=".autoenv"
export AUTOENV_ASSUME_YES=1

export CONDA_DIR="$HOME/miniconda3"
export GEM_HOME="$HOME/.gem"
export GOPATH="$HOME/go"
export DEFAULT_IMG="python:3.8"
export PYTHON_NEOVIM="$HOME/miniconda3/envs/neovim/bin/python"
export MYGITPROJECTS="$HOME/github"
export MYVIMRC="$HOME/.config/nvim/init.vim"
