#!/usr/bin/env bash
export SSH_KEY_PATH="~/.ssh/rsa_id"
export EDITOR="nvim"

export AUTOENV_ENV_FILENAME=".autoenv"
export AUTOENV_ASSUME_YES=1

export GEM_HOME="$HOME/.gem"
export DEFAULT_IMG=mmngreco/dev:latest
export MYGITPROJECTS="$HOME/github"
export MYVIMRC="$HOME/.config/nvim/init.lua"
export KITTY_LISTEN_ON=unix:/tmp/mykitty-$PPID

# export MOIRA_HOURS_PER_DAY=6
# if not in macos only linux
if [[ "$OSTYPE" != "darwin"* ]]; then
    # linux config only
    export CONDA_DIR="$HOME/miniconda3"
    export GDK_BACKEND=x11
    export GTK_THEME=Materia:dark:compact
fi
export AWS_CONFIG_FILE=$HOME/.aws/credentials
