#!/usr/bin/env zsh
# -----------------------------------------------------------------------------
# PROMPT
# amuse modified

# ZSH_THEME_GIT_PROMPT_PREFIX=" on %{$fg[magenta]%}\uE0A0 "
# ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%}"
# ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[red]%}!"
# ZSH_THEME_GIT_PROMPT_UNTRACKED="%{$fg[green]%}?"
# ZSH_THEME_GIT_PROMPT_CLEAN=""
# ZSH_THEME_RUBY_PROMPT_PREFIX="%{$fg_bold[red]%}‹"
# ZSH_THEME_RUBY_PROMPT_SUFFIX="›%{$reset_color%}"
# PROMPT='
# %{$fg_bold[green]%}%~%{$reset_color%}$(git_prompt_info) %{$fg_bold[red]%}%*%{$reset_color%}
# $ '
# RPROMPT='$(ruby_prompt_info)'
function preexec() {
    typeset -gi CALCTIME=1
    typeset -gi CMDSTARTTIME=SECONDS
}

function precmd() {
    if (( CALCTIME )) ; then
        typeset -gi ETIME=SECONDS-CMDSTARTTIME
    fi
    typeset -gi CALCTIME=0
}

# PS1='${ETIME} %'

# robbyrussell
# PROMPT='%{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)'
# PROMPT+='%{$fg[magenta]%}(%T|${ETIME:-0}s)%{$reset_color%}'
# PROMPT+=' %(?:%{$fg[green]%}$:%{$fg[red]%}$)%{$reset_color%} '
PROMPT='%(?:%{$fg[green]%}$:%{$fg[red]%}$)%{$reset_color%} '

# ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[blue]%}(%{$fg[red]%}"
# ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
# ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[blue]%}) %{$fg[yellow]%}X"
# ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[blue]%})"
