#!/usr/bin/env zsh
export ZSH=~/.oh-my-zsh

source $DOTFILES/shell/common
source $DOTFILES/shell/zsh_prompt

[ -f $HOME/.fzf.zsh ] && source $HOME/.fzf.zsh

# define always before before sourcing oh-my-zsh.sh
plugins=(
    zsh-autosuggestions
)
source $ZSH/oh-my-zsh.sh


#------------------------------------------------------------------------------
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/mgreco/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/mgreco/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/mgreco/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/mgreco/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# ----------------------------------------------------------------------------
# shortcuts
join-lines() {
  local item
  while read item; do
    echo -n "${(q)item} "
  done
}

bind-git-wrapper() {
  local c
  for c in $@; do
    eval "fzf-g$c-widget() { local result=\$(_g$c | join-lines); zle reset-prompt; LBUFFER+=\$result }"
    eval "zle -N fzf-g$c-widget"
    eval "bindkey '^g^$c' fzf-g$c-widget"
  done
}
bind-git-wrapper f b t r h s
unset -f bind-git-wrapper
# bindkey -s ^t^w "txw\n"
# bindkey -s ^t^s "txs\n"
