#!/usr/bin/env bash
# https://git-secret.io/installation
echo ""
echo "Installing git-secret..."
echo ""

clone_dir=/tmp/dotfiles/git-secret
sudo apt install apt-transport-https ca-certificates --yes
[ -f "${clone_dir}" ] && rm -rf ${clone_dir}
git clone --depth 1 https://github.com/sobolevn/git-secret.git ${clone_dir}

set -e
pushd ${clone_dir}
make build
PREFIX="/usr/local" sudo make install
popd
rm -rf ${clone_dir}
