#!/usr/bin/env bash
# https://github.com/xiph/rnnoise

clone_dir=/tmp/rnnoise
git clone --depth 1 https://github.com/xiph/rnnoise $clone_dir
pushd $clone_dir
./autogen.sh
./configure
make
sudo make install
popd
rm -rf $clone_dir
