#!/usr/bin/env bash
set -e
clone_dir=/tmp/github/tmux

sudo apt --yes install automake autotools-dev libevent-dev libncurses5-dev build-essential bison pkg-config
[ -d $clone_dir ] && rm -rf $clone_dir
git clone --depth 1 https://github.com/tmux/tmux.git $clone_dir
pushd $clone_dir
sh autogen.sh
./configure && make
sudo make install
popd
