git submodule add ./config/nvim/plugged/w3m.vim
git submodule add ./config/nvim/plugged/impsort.vim/bin/jedi
git submodule add ./config/nvim/plugged/impsort.vim/bin/parso
git submodule add ./config/nvim/plugged/impsort.vim
git submodule add ./config/nvim/plugged/chromatica.nvim
git submodule add ./config/nvim/plugged/vim-trailing-whitespace
git submodule add ./config/nvim/plugged/async.vim
git submodule add ./config/nvim/plugged/echodoc.vim
git submodule add ./config/nvim/plugged/vim-airline-themes
git submodule add ./config/nvim/plugged/nvim-yarp
git submodule add ./config/nvim/plugged/vim-surround
git submodule add ./config/nvim/plugged/vim-airline
git submodule add ./config/nvim/plugged/tagbar
git submodule add ./config/nvim/plugged/ncm2
git submodule add ./config/nvim/plugged/jedi-vim/pythonx/jedi
git submodule add ./config/nvim/plugged/jedi-vim/pythonx/parso
git submodule add ./config/nvim/plugged/jedi-vim
git submodule add ./config/nvim/plugged/vim-gitgutter
git submodule add ./config/nvim/plugged/tabular
git submodule add ./config/nvim/plugged/supertab
git submodule add ./config/nvim/plugged/ale
git submodule add ./config/nvim/plugged/vim-conda
git submodule add ./config/nvim/plugged/neoinclude.vim
git submodule add ./config/nvim/plugged/vim-repeat
git submodule add ./config/nvim/plugged/slimux
git submodule add ./config/nvim/plugged/vimcmdline
git submodule add ./config/nvim/plugged/vim-pydocstring
git submodule add ./config/nvim/plugged/ultisnips
git submodule add ./config/nvim/plugged/vim-indent-guides
git submodule add ./config/nvim/plugged/vim-misc
git submodule add ./config/nvim/plugged/vim-autopep8
git submodule add ./config/nvim/plugged/vim-unimpaired
git submodule add ./config/nvim/plugged/nerdtree-execute
git submodule add ./config/nvim/plugged/vim-nerdtree-direnter
git submodule add ./config/nvim/plugged/vim-fugitive
git submodule add ./config/nvim/plugged/ncm2-bufword
git submodule add ./config/nvim/plugged/vim-abolish
git submodule add ./config/nvim/plugged/neomake
git submodule add ./config/nvim/plugged/rainbow
git submodule add ./config/nvim/plugged/vim-instant-markdown
git submodule add ./config/nvim/plugged/ncm2-path
git submodule add ./config/nvim/plugged/ncm2-jedi
git submodule add ./config/nvim/plugged/vim-nerdtree-syntax-highlight
git submodule add ./config/nvim/plugged/vim-devicons
git submodule add ./config/nvim/plugged/vim-notes
git submodule add ./config/nvim/plugged/vim-sensible
git submodule add ./config/nvim/plugged/indentLine
git submodule add ./config/nvim/plugged/vim-tmux-navigator
git submodule add ./config/nvim/plugged/vim-commentary
git submodule add ./config/nvim/plugged/vim-snippets
git submodule add ./config/nvim/plugged/vim-markdown-composer
git submodule add ./config/nvim/plugged/vim-signature
git submodule add ./config/nvim/plugged/fzf
git submodule add ./config/nvim/plugged/nerdtree
git submodule add ./config/nvim/plugged/vim-sublime-monokai
git submodule add ./config/nvim/plugged/vim-colors-solarized
git submodule add ./config/nvim/plugged/ctrlp.vim
git submodule add ./config/nvim/plugged/undotree
git submodule add ./config/tmux/plugins/tpm
git submodule add ./tmux/plugins/tmux-continuum
git submodule add ./tmux/plugins/tmux-resurrect/lib/tmux-test
git submodule add ./tmux/plugins/tmux-resurrect
git submodule add ./tmux/plugins/tmux-yank
git submodule add ./tmux/plugins/tmux-sensible
git submodule add ./tmux/plugins/tpm/lib/tmux-test
git submodule add ./tmux/plugins/tpm
git submodule add ./tmux/plugins/tmux-logging
git submodule add ./tmux/.tmux/plugins/tmux-continuum
git submodule add ./tmux/.tmux/plugins/tmux-resurrect/lib/tmux-test
git submodule add ./tmux/.tmux/plugins/tmux-resurrect
git submodule add ./tmux/.tmux/plugins/tmux-yank
git submodule add ./tmux/.tmux/plugins/tmux-sensible
git submodule add ./tmux/.tmux/plugins/tpm/lib/tmux-test
git submodule add ./tmux/.tmux/plugins/tpm
git submodule add ./tmux/.tmux/plugins/tmux-logging
