#!/usr/bin/env bash
function install_absent () {
    if ! command -v $1 &> /dev/null
    then
        . $1
    fi
}


install_absent zsh
install_absent fzf
install_absent git-secret
install_absent glab
install_absent rust
install_absent golang
install_absent gh
install_absent keepassxc
install_absent latex
install_absent conda
install_absent nvim
install_absent node
install_absent tmux
install_absent ctags
