#!/usr/bin/env bash
sudo apt install libxcb-xinerama0-dev \
                 libxcb-icccm4-dev \
                 libxcb-randr0-dev \
                 libxcb-util0-dev \
                 libxcb-ewmh-dev \
                 libxcb-keysyms1-dev \
                 libxcb-shape0-dev \
                 build-essentials \
                 -y
git clone https://github.com/baskerville/bspwm.git $HOME/bspwm
git clone https://github.com/baskerville/sxhkd.git $HOME/sxhkd
pushd $HOME/bspwm && make && sudo make install && popd
pushd $HOME/sxhkd && make && sudo make install && popd

sudo apt install feh rofi dunst -y

# uninstalling
# git clone https://github.com/baskerville/bspwm.git $HOME/bspwm
# git clone https://github.com/baskerville/sxhkd.git $HOME/sxhkd
# cd bspwm && sudo make uninstall
# cd ../sxhkd && sudo make uninstall
