#!/usr/bin/env bash
curl -L https://github.com/cmus/cmus/archive/refs/tags/v2.9.1.tar.gz -o cmus.tar.gz

extract cmus.tar.gz
cd cmus-2.9.1
sudo apt install libroar-dev
./configure
make
sudo make install
