#!/usr/bin/env bash

sudo apt install libopencv-dev build-essential v4l2loopback-dkms curl v4l-utils

clone_dir=/tmp/dotfiles/backscrub
if [ ! -d $clone_dir ]; then
    git clone --recursive --depth 1 https://github.com/floe/backscrub.git $clone_dir
    pushd $clone_dir
    make
    popd $clone_dir
fi
