#!/usr/bin/env bash
set -e

clone_dir=/tmp/dotfiles/universal_ctags
git clone --depth 1 https://github.com/universal-ctags/ctags.git $clone_dir

pushd $clone_dir &> /dev/null
./autogen.sh
./configure
make
sudo make install # may require extra privileges depending on where to install
popd

rm -rf $clone_dir
