#!/usr/bin/env bash
# https://github.com/dandavison/delta/tree/0.8.3#side-by-side-view
ver="0.14.0"
curl -L https://github.com/dandavison/delta/releases/download/${ver}/git-delta_${ver}_amd64.deb -o git-delta_${ver}_amd64.deb
sudo dpkg -i git-delta_${ver}_amd64.deb
rm git-delta_${ver}_amd64.deb
