#!/usr/bin/env bash
sudo apt-get update
sudo apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common
sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu eoan test"
sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io
# add user togroup
sudo groupadd docker
sudo usermod -aG docker $USER
newgrp docker
docker run hello-world
