#!/usr/bin/env bash
# https://askubuntu.com/questions/191778/how-to-install-many-font-files-quickly-and-easily
set -e
dir="$HOME/github/mmngreco/fonts"
[ -d "$dir" ] && rm -rf $dir
git clone https://github.com/mmngreco/fonts $dir
[ ! -d "$HOME/.local/share/fonts" ] && mkdir -p "$HOME/.local/share/fonts"
cp $dir/**/*.{ttf,otf} $HOME/.local/share/fonts
fc-cache -f -v
