#!/usr/bin/env bash

sudo apt-get -y update \
&& sudo apt-get -y \
    --force-yes install \
    --fix-missing \
    apt-utils \
    build-essential \
    bzip2 \
    ca-certificates \
    curl \
    freetds-bin \
    freetds-dev \
    git \
    gnupg \
    libbz2-dev \
    libfontconfig \
    liblzma-dev \
    libreadline-dev \
    libsqlite3-dev \
    libssl-dev \
    libffi-dev \
    make \
    net-tools \
    openssh-client \
    readline-common \
    supervisor \
    tdsodbc \
    unixodbc \
    unixodbc-dev \
    wget \
    xz-utils \
    zlib1g-dev


echo "[FreeTDS]"                                             > /etc/odbcinst.ini
echo "Description = TDS driver (Sybase/MS SQL)"              >> /etc/odbcinst.ini
echo "Driver = /usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so" >> /etc/odbcinst.ini
echo "Setup = /usr/lib/x86_64-linux-gnu/odbc/libtdsS.so"     >> /etc/odbcinst.ini
