#!/usr/bin/env bash -x
# https://git-secret.io/installation
echo ""
echo "Installing git-secret..."
echo ""

cloneDir=${HOME}/git-secret
sudo apt install apt-transport-https ca-certificates --yes
[ -f "${cloneDir}" ] && rm -rf ${cloneDir}
git clone --depth 1 https://github.com/sobolevn/git-secret.git ${cloneDir}
pushd ${cloneDir}
make build
PREFIX="/usr/local" sudo make install
popd
rm -rf ${cloneDir}
