#!/usr/bin/env bash -x
# https://git-secret.io/installation
echo ""
echo "Installing git-secret..."
echo ""

path=${HOME}/git-secret
sudo apt install apt-transport-https ca-certificates --yes
git clone --depth 1 https://github.com/sobolevn/git-secret.git ${path}
popd ${path}
make build
PREFIX="/usr/local" sudo make install
pushd
rm -rf ${path}
