#!/usr/bin/env bash
# https://git-secret.io/installation
echo ""
echo "Installing git-secret..."
echo ""

sudo apt install apt-transport-https ca-certificates --yes
git clone --depth 1 https://github.com/sobolevn/git-secret.git git-secret
cd git-secret
make build
PREFIX="/usr/local" sudo make install
cd ..
rm -rf git-secret
