#!/usr/bin/env bash

dir=/tmp/gsutil
[ -d "$dir" ] && rm -r $dir
mkdir -p /tmp/gsutil

set -e
pushd $dir &> /dev/null

curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-410.0.0-linux-x86_64.tar.gz
tar -xf $dir/google-cloud-cli-410.0.0-linux-x86.tar.gz
$dir/google-cloud-sdk/install.sh
$dir/google-cloud-sdk/bin/gcloud init
