#!/usr/bin/env bash
# https://i3wm.org/docs/userguide.html#_using_i3
/usr/lib/apt/apt-helper download-file https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2021.02.02_all.deb keyring.deb SHA256:cccfb1dd7d6b1b6a137bb96ea5b5eef18a0a4a6df1d6c0c37832025d2edaa710
sudo dpkg -i ./keyring.deb
echo "deb http://debian.sur5r.net/i3/ $(grep '^DISTRIB_CODENAME=' /etc/lsb-release | cut -f2 -d=) universe" >> /etc/apt/sources.list.d/sur5r-i3.list
sudo apt update

echo ""
echo "Installing dependencies..."
echo ""

sudo apt install --yes i3
sudo apt install --yes i3-wm dunst i3lock i3status suckless-tools
sudo apt install --yes compton hsetroot rxvt-unicode xsel rofi fonts-font-awesome fonts-noto fonts-mplus xsettingsd lxappearance scrot OpenShot blueman ffmpeg volumeicon-alsa figlet

echo ""
echo "Linking files..."
echo ""

