#!/usr/bin/env bash

sudo apt update
sudo apt install --yes \
    suckless-tools \
    picom \
    hsetroot \
    rxvt-unicode \
    xsel \
    rofi \
    fonts-font-awesome \
    fonts-noto \
    fonts-mplus \
    xsettingsd \
    lxappearance \
    scrot \
    blueman \
    ffmpeg \
    volumeicon-alsa \
    pavucontrol \
    xbacklight \
    xautolock \
    xdotool \
    i3blocks \
    figlet

# https://github.com/Airblader/i3/wiki/Building-from-source
sudo apt install --yes \
    libxcb1-dev \
	libxcb-keysyms1-dev \
	libpango1.0-dev \
    libxcb-util0-dev \
	libxcb-icccm4-dev \
	libyajl-dev \
    libstartup-notification0-dev \
	libxcb-randr0-dev \
    libev-dev \
	libxcb-cursor-dev \
	libxcb-xinerama0-dev \
    libxcb-xkb-dev \
	libxkbcommon-dev \
	libxkbcommon-x11-dev \
    autoconf \
	libxcb-xrm0 \
	libxcb-xrm-dev \
	automake \
	libxcb-shape0-dev

dir=/tmp/i3
set -e
[ -d $dir ] || rm -rf $dir
git clone https://github.com/i3/i3 $dir
pushd $dir &> /dev/null
mkdir -p build && cd build
meson ..
ninja
sudo meson install
