#!/usr/bin/env bash
# https://github.com/neovim/neovim/wiki/Installing-Neovim#ubuntu

echo "========================================================================"
echo "Installing dependencies..."
echo "========================================================================"

sudo apt remove --purge neovim --yes
sudo apt-get install --yes ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip

set -e

echo "========================================================================"
echo "Installing neovim..."
echo "========================================================================"

NEOVIM_DIR="$HOME/github/neovim/neovim"
NEOVIM_URL="https://github.com/neovim/neovim.git"
NEOVIM_VER=$(git -c 'versionsort.suffix=-' \
    ls-remote --exit-code --refs --sort='version:refname' --tags $NEOVIM_URL '*.*.*' \
    | tail --lines=1 \
    | cut --delimiter='/' --fields=3)

[ -d $NEOVIM_DIR ] && rm -rf $NEOVIM_DIR
git clone --depth 1 -b $NEOVIM_VER $NEOVIM_URL $NEOVIM_DIR

pushd  $NEOVIM_DIR
    make CMAKE_BUILD_TYPE=Release -j2
    sudo make install
popd


echo "========================================================================"
echo "Installing plug..."
echo "========================================================================"

PLUG_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/nvim/site/autoload/plug.vim"
PLUG_URL="https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

curl -fLo $PLUG_DIR --create-dirs $PLUG_URL


