#!/usr/bin/env bash

# install node and npm
if [ ! -x "$(command -v npm)" ]
then
    curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    sudo apt update
    sudo apt install nodejs
    curl -L https://npmjs.org/install.sh | sudo sh
fi

# install gyp
if [ ! -x "$(command -v gyp)" ]
then
    sudo npm install -g node-gyp
    # echo 'export npm_config_node_gyp="/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js"' >> $DOTFILES/shell/variables
fi


# install tree-sitter
if [ ! -f /usr/local/bin/tree-sitter ]
then
    URL=https://github.com/tree-sitter/tree-sitter/releases/download/v0.18.3/tree-sitter-linux-x64.gz
    curl -L $URL | sudo gunzip - > /usr/local/bin/tree-sitter
    sudo chmod ugo+x /usr/local/bin/tree-sitter
fi


# install browser-sync
if [ ! -x "$(command -v browser-sync)" ]
then
    sudo npm install -g browser-sync
    # echo 'export SERVER_IP=$(hostname -I)' >> $DOTFILES/shell/aliases
    # echo 'alias serve="browser-sync start --server --files . --no-notify --host $SERVER_IP --port 9000"' >> $DOTFILES/shell/aliases
fi
