#!/usr/bin/env bash

# https://github.com/lawl/NoiseTorch

pushd ~/ > /dev/null
wget https://github.com/lawl/NoiseTorch/releases/download/0.11.6/NoiseTorch_x64.tgz
tar -C $HOME -xzf NoiseTorch_x64.tgz
sudo setcap 'CAP_SYS_RESOURCE=+ep' ~/.local/bin/noisetorch
popd > /dev/null

# test locally with
# gst-launch-1.0 pulsesrc ! pulsesink
