#!/usr/bin/env bash
#https://www.linuxbabe.com/cloud-storage/install-google-drive-ocamlfuse-on-ubuntu-16-04-linux-mint-18
sudo add-apt-repository -y ppa:alessandro-strada/ppa
sudo apt update && sudo apt install google-drive-ocamlfuse
google-drive-ocamlfuse
mkdir ~/google-drive
google-drive-ocamlfuse ~/google-drive/
# unmount fusermount -u ~/google-drive
echo "google-drive-ocamlfuse ~/google-drive/" >> ~/.profile
