#!/usr/bin/env bash
set -e
dir="${HOME}/.oh-my-zsh"
[ -d "$dir" ] && rm -rf $dir
sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
