#!/usr/bin/env bash

# https://github.com/polybar/polybar/wiki/Compiling
# dependencies
sudo apt install \
        build-essential \
		git \
		cmake \
		cmake-data \
		pkg-config \
		python3-sphinx \
		python3-packaging \
		libcairo2-dev \
		libxcb1-dev \
		libxcb-util0-dev \
		libxcb-randr0-dev \
		libxcb-composite0-dev \
		python3-xcbgen \
		xcb-proto \
		libxcb-image0-dev \
		libxcb-ewmh-dev \
		libxcb-icccm4-dev \
        -y

sudo apt install \
        libxcb-xkb-dev \
		libxcb-xrm-dev \
		libxcb-cursor-dev \
		libasound2-dev \
		libpulse-dev \
		libjsoncpp-dev \
		libmpdclient-dev \
		libcurl4-openssl-dev \
		libnl-genl-3-dev \
        -y

# compiling

# Make sure to type the `git' command as-is to clone all git submodules too

clone_dir=/tmp/dotfiles/polybar

set -e
git clone --depth 1 --recursive https://github.com/polybar/polybar ${clone_dir}

cd ${clone_dir}

mkdir build
cd build

# https://github.com/polybar/polybar/issues/2057#issuecomment-613138335
conda deactivate

cmake ..
make -j$(nproc)
# Optional. This will install the polybar executable in /usr/local/bin
sudo make install

pushd
pushd
