#!/usr/bin/env bash
set -e

sudo apt install \
    make \
    autoconf \
    automake \
    pkg-config \
    flex \
    bison


dir=/tmp/rofi
[ -d $dir ] && rm -rf $dir
git clone --depth 1 https://github.com/davatorium/rofi $dir

pushd $dir
meson setup build
ninja -C build
sudo ninja -C build install


[ ! -d "~/rofi/kaomoji-rofi" ] && git clone https://gitlab.com/ceda_ei/kaomoji-rofi ~/rofi/kaomoji-rofi
