#!/usr/bin/env bash
rm -rf ~/github/tmux
sudo apt --yes install automake autotools-dev libevent-dev libncurses5-dev build-essential bison pkg-config
git clone --depth 1 https://github.com/tmux/tmux.git ~/github/tmux
pushd ~/github/tmux
sh autogen.sh
./configure && make
sudo make install
popd
