#!/usr/bin/env bash
set -e

dir="$HOME/.tmux/plugins/tpm"
[ -d $dir ] && rm -rf $dir
git clone https://github.com/tmux-plugins/tpm $dir

tmux start-server

# create a new session but don't attach to it either
tmux new-session -d
# install the plugins
$dir/scripts/install_plugins.sh

# kill the server
# tmux kill-server
