#!/usr/bin/env bash
set -e
path=/tmp/github/tmux

sudo apt --yes install automake autotools-dev libevent-dev libncurses5-dev build-essential bison pkg-config
[ -d $path ] && rm -rf $path
git clone --depth 1 https://github.com/tmux/tmux.git $path
pushd $path
sh autogen.sh
./configure && make
sudo make install
popd
