#!/usr/bin/env bash
# check if command sudo exists if not mock it
if [ ! -x "$(command -v sudo)" ]; then
    echo sudo not found, mocking it
    alias sudo=''
fi

sudo apt install zsh -y
sudo chsh -s $(which zsh) $USERNAME

set -e

[ ! -d "~/.zsh/" ] && mkdir ~/.zsh/
git clone https://github.com/catppuccin/zsh-syntax-highlighting.git ~/.zsh/zsh-syntax-highlighting/
