#!/usr/bin/env bash
sudo apt install zsh -y
sudo chsh -s $(which zsh) $USERNAME

git clone https://github.com/catppuccin/zsh-syntax-highlighting.git /tmp/zsh-syntax-highlighting/
cd /tmp/zsh-syntax-highlighting/
cp -v catppuccin-zsh-syntax-highlighting.zsh ~/.zsh
