#!/usr/bin/env bash
# check if sudo exists
if [ $(id -u) -ne 0 ]; then
    apt install zsh -y
    chsh -s $(which zsh) $USERNAME
else
    sudo apt install zsh -y
    sudo chsh -s $(which zsh) $USERNAME
fi


set -e
git clone https://github.com/catppuccin/zsh-syntax-highlighting.git /tmp/zsh-syntax-highlighting/
cd /tmp/zsh-syntax-highlighting/

[ ! -d "~/.zsh/" ] && mkdir ~/.zsh/
cp -v catppuccin-zsh-syntax-highlighting.zsh ~/.zsh/
