#!/usr/bin/env sh
set -e -v
curl -sL -o nvim-macos-arm64.tar.gz https://github.com/neovim/neovim/releases/download/nightly/nvim-macos-arm64.tar.gz
tar -xzf /tmp/nvim-macos-arm64.tar.gz -C /tmp/
sudo rm -rf /opt/nvim
sudo cp -r /tmp/nvim-macos-arm64 /opt/nvim
