curl -LsSf https://astral.sh/uv/install.sh | sh
uv tool install black  --no-cache
uv tool install cookiecutter  --no-cache
uv tool install copier  --no-cache
uv tool install flake8  --no-cache
uv tool install httpie  --no-cache
uv tool install isort  --no-cache
uv tool install jupytext  --no-cache
uv tool install lookatme  --no-cache
uv tool install pydocstyle  --no-cache
uv tool install pydoro  --no-cache
uv tool install ruff  --no-cache
uv tool install sgpt  --no-cache
uv tool install sqlparse  --no-cache
uv tool install trash-cli  --no-cache
uv tool install vdsql  --no-cache
uv tool install visidata  --no-cache
uv tool install nbdime  --no-cache
