#!/usr/bin/env bash
# https://askubuntu.com/questions/191778/how-to-install-many-font-files-quickly-and-easily
set -e
clone_dir="$HOME/github/mmngreco/fonts"

[ -d "${clone_dir}" ] && rm -rf ${clone_dir}
git clone ssh://git@github.com/mmngreco/fonts ${clone_dir}

[ ! -d "$HOME/.local/share/fonts" ] && mkdir -p "$HOME/.local/share/fonts"
cp ${clone_dir}/**/*.{ttf,otf} $HOME/.local/share/fonts

fc-cache -f -v
