#!/usr/bin/env bash
sudo apt-get install -y texlive-latex-base \
                     texlive-fonts-recommended \
                     texlive-fonts-extra \
                     texlive-latex-extra \
                     texlive-xetex \
                     latexmk
