#!/usr/bin/env sh
# check if command sudo exists if not mock it
if ! command -v sudo &> /dev/null
then
    # Define a function that simulates sudo behavior
    sudo() {
        if [ "$#" -eq 0 ]; then
            echo "Usage: sudo command [arguments]"
            return 1
        fi
        command="$1"
        shift
        echo "Running command as root: $command $@"
        $command "$@"
    }
fi

sudo apt install zsh -y
sudo chsh -s $(which zsh) $USERNAME

set -e

[ ! -d "~/.zsh/" ] && mkdir ~/.zsh/
git clone https://github.com/catppuccin/zsh-syntax-highlighting.git ~/.zsh/zsh-syntax-highlighting/
