#!/usr/bin/env bash
source $DOTFILES/linux/shell/variables
source $DOTFILES/linux/shell/customization
source $DOTFILES/linux/shell/functions
source $DOTFILES/linux/shell/aliases
source $DOTFILES/linux/shell/nnn

for hidden in $(find $DOTFILES/linux/ -name "*.hide" -type f)
do
    source $hidden
done

# bin
addToPath "/usr/local/bin"
addToPath "$HOME/bin"
addToPath "$HOME/.cargo/bin"
addToPath "$HOME/.local/bin"
addToPath "$HOME/.deno/bin"
# go
addToPathFront "$HOME/go/bin"
addToPathFront "/home/mgreco/.go/bin"
addToPathFront "/usr/local/go/bin"
# db
addToPathFront "/opt/mssql-tools/bin"
addToPath "/opt/mssql-tools/bin"
# ruby
addToPathFront "$GEM_HOME/bin"
# projects folders
addToMyGitProjects $HOME/github
addToMyGitProjects $HOME/gitlab
