#!/usr/bin/env bash
ver="v2.1.8"
wget https://github.com/federico-terzi/espanso/releases/download/${ver}/espanso-debian-x11-amd64.deb
sudo apt install ./espanso-debian-x11-amd64.deb
rm ./espanso-debian-x11-amd64.deb

# Register espanso as a systemd service (required only once)
espanso service register
# Start espanso
espanso start

