#!/usr/bin/env bash

set -e
clone_dir=/tmp/dotfiles/i3-volume
if [ ! -d "${clone_dir}" ]; then
    git clone https://github.com/hastinbe/i3-volume.git $clone_dir
    pushd $clone_dir &> /dev/null
    # cat i3volume-pulseaudio.conf >> ~/.config/i3/config
    cat i3volume-alsa.conf >> ~/.config/i3/config
    popd
fi
