#!/usr/bin/env sh

# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
# yabai -m signal --add event=display_added action="sleep 2 && $HOME/.config/yabai/create_spaces.sh"
# yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
# yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
# yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# MOUSE CONFIGURATION {{{
# center mouse on window with focus
yabai -m config mouse_follows_focus          off
# yabai -m config focus_follows_mouse          autofocus
yabai -m config focus_follows_mouse          off

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize
# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m mouse_drop_action swap

# }}}

# global settings
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_zoom_persist          on
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_animation_duration    0.0
# yabai -m config window_animation_frame_rate  50
yabai -m config window_animation_frame_rate  0
yabai -m config window_opacity_duration      0.0

yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_opacity               off
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config window_border_width          0
yabai -m config window_border_radius         0
yabai -m config window_border_blur           off
yabai -m config window_border_hidpi          on

yabai -m config split_ratio                  0.50
yabai -m config split_type                   auto
yabai -m config auto_balance                 off
yabai -m config top_padding                   0
yabai -m config bottom_padding                0
yabai -m config left_padding                  0
yabai -m config right_padding                 0
yabai -m config window_gap                    0
yabai -m config layout                       bsp

# RULES {{{
# fix space number for the following applications
yabai -m rule --add app="^Brave$" space=4
yabai -m rule --add app="^Firefox$" space=5
yabai -m rule --add app="^Chrome$" space=2
yabai -m rule --add app="^Slack$" space=3
# yabai -m rule --add app="^Firefox$" space=4


# disable window management for the following applications
yabai -m rule --add app="^Telegram$" manage=off
yabai -m rule --add app="^iTerm2$" manage=off
yabai -m rule --add app="^PureVPN Beta$" manage=off
yabai -m rule --add app="^Spotify$" manage=off space=7
yabai -m rule --add app="^CopyQ$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Jiffy$" manage=off
yabai -m rule --add app="^Krisp$" manage=off
yabai -m rule --add app="^Huddle$" manage=off
yabai -m rule --add app="^Alfred$" manage=off
yabai -m rule --add app="^istats$" manage=off
yabai -m rule --add app="^Terminal$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Espanso$" manage=off
yabai -m rule --add app="^CameraController$" manage=off
yabai -m rule --add app="^Strongbox$" manage=off sticky=on
yabai -m rule --add app="^licecap$" manage=off
yabai -m rule --add app="^kitty$" manage=on space=1
yabai -m rule --add app="^Gimp.*script\-fu.*$" manage=off space=8
yabai -m rule --add app="^Obs.*$" manage=off space=9
yabai -m rule --add app="^KeyboardCleanTool$" manage=off

# native macos apps
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Photos$" manage=off
yabai -m rule --add app="^Pictures$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^FaceTime$" manage=off
yabai -m rule --add app="^Reminders$" manage=off
yabai -m rule --add app="^Gifox$" manage=off

# Space names
yabai -m space 1 --label term
yabai -m space 2 --label browser
yabai -m space 3 --label chat
yabai -m space 4 --label misc
yabai -m space 5 --label work
yabai -m space 6 --label telegram
yabai -m space 7 --label db
yabai -m space 8 --label personal
yabai -m space 9 --label obs
yabai -m space 0 --label work
# }}}

noti -t "yabai" -m "configuration loaded"
