#!/usr/bin/env sh

# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# MOUSE CONFIGURATION {{{
# center mouse on window with focus
yabai -m config mouse_follows_focus on
# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize
# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m mouse_drop_action swap
# }}}

# global settings
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_zoom_persist          on
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_animation_duration    0.0
yabai -m config window_animation_frame_rate  120
yabai -m config window_opacity_duration      0.0

yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_opacity               off
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config window_border_width          4
yabai -m config window_border_radius         12
yabai -m config window_border_blur           off
yabai -m config window_border_hidpi          on

yabai -m config split_ratio                  0.50
yabai -m config split_type                   auto
yabai -m config auto_balance                 off
yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   06
yabai -m config layout                       bsp

# RULES {{{
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Jiffy$" manage=off
# }}}

echo "yabai configuration loaded.."
