#!/usr/bin/env bash

set -v -e -x
dir=/tmp/catppuccin/zsh
[ -d $dir ] && rm -rf $dir
git clone https://github.com/catppuccin/zsh-syntax-highlighting.git $dir
cd $dir/themes/
[ -d ~/.zsh ] || mkdir -p ~/.zsh/
cp -v catppuccin_mocha-zsh-syntax-highlighting.zsh ~/.zsh/

dir=/tmp/catppuccin/rofi
[ -d $dir ] && rm -rf $dir
git clone https://github.com/catppuccin/rofi.git $dir
cd $dir/basic
bash ./install.sh
