#!/usr/bin/env bash
clone_dir=/tmp/dotfiles/diagon

[[ -d "${clone_dir}" ]] && sudo rm -rf ${clone_dir}
# clone project
git clone --depth 1 https://github.com/ArthurSonzogni/Diagon ${clone_dir}

# install dependencies
sudo apt install make uuid-dev libboost-graph-dev cmake

set -e
pushd ${clone_dir} > /dev/null
    mkdir ./build
    cd ./build
    cmake .. -DCMAKE_BUILD_TYPE=Release
    make -j
    sudo make install
popd
