#!/usr/bin/env bash

dir=~/st
[ -d $dir ] && rm -rf $dir
git clone --depth 1 https://git.suckless.org/st $dir

pushd $dir > /dev/null

# patch < ~/.dotfiles/ubuntu/st-patches/catppuccin.diff
patch < ~/.dotfiles/ubuntu/st-patches/fix-keyboard-input.diff
patch < ~/.dotfiles/ubuntu/st-patches/clipboard.diff
patch < ~/.dotfiles/ubuntu/st-patches/alpha.diff
patch < ~/.dotfiles/ubuntu/st-patches/defaultfont.diff
patch < ~/.dotfiles/ubuntu/st-patches/ligatures.diff

sudo make clean install
popd > /dev/null
