#!/usr/bin/env bash

sudo apt install libxcb-util0-dev xcb libxcb-keysyms1-dev

clone_dir=/tmp/dotfiles/sxhkd
git clone git@github.com:baskerville/sxhkd.git $clone_dir
set -e
pushd $clone_dir
make
sudo make install
popd
rm -rf $clone_dir
