#!/usr/bin/env bash

translate_post() {
    file=/tmp/gpt4-translate.md
    sgpt --model gpt-4 --chat blog "translate to english and fix grammar from this markdown: \n\n $(cat $1)" | tee $file
    echo File: $file
}

kx() {
    export KUBECONFIG=$(find ~/.kube/configs/ | fzf --height 10 --layout reverse)
}

blog() {
    blog_home="$HOME/github/mmngreco/mmngreco.github.io"
    blog_home="$HOME/github/mmngreco/blog"
    EDITOR=nvim
    case $1 in
        help)
            echo "Usage: blog <command>"
            echo ""
            echo "Commands:"
            echo "  session  Create a new tmux session"
            echo "  new      Create a new post"
            echo "  serve    Serve the blog"
            echo "  edit     Edit a post"
            ;;
        session)
            # check if tmux server is running
            tmux has-session -t blog && tmux kill-session -t blog
            tmux info &> /dev/null || tmux start-server \; new-session -d
            tmux new-session -s blog -d -c $blog_home
            tmux new-window -a -t blog -c $blog_home
            tmux new-window -a -t blog -c $blog_home

            tmux rename-window -t blog:1 "server"
            tmux rename-window -t blog:2 "edit"
            tmux rename-window -t blog:3 "new"

            tmux send-keys -t blog:edit "blog edit" C-m
            tmux send-keys -t blog:new "blog new" C-m
            tmux send-keys -t blog:server "blog serve" C-m

            window=${2:-new}
            tmux switch-client -t blog:$window || tmux attach-session -t blog:$window
            ;;

        quit)
            tmux kill-session -t blog
            ;;
        new)
            new_post="$(date +"%Y-%m-%d")-post.md"
            file=content/posts/$new_post
            hugo new content posts/$new_post
            $EDITOR $file
            # git add $file
            # git commit -m "enh(content): Add $new_post"
            ;;
        edit)
            file=$(find . -type f | fzf --preview 'bat --color=always {}')
            $EDITOR $file
            # git add $file && git commit -m "enh: update $file"
            ;;
        serve)
            hugo server -D
            ;;
        open)
            open http://localhost:1313 &
            ;;
        *)
            blog session
            ;;
    esac
}

sourcePattern() {
    folder=$1
    pattern=$2
    for hidden in $(find $folder -name $pattern -type f)
    do
        source $hidden
    done
}

addToMyGitProjects(){
    if [[ "$MYGITPROJECTS" != *"$1"*  ]]; then
        # only if exists the folder it will be exported
        [ -d "$1" ] && export MYGITPROJECTS="$MYGITPROJECTS:$1"
    fi
}

addToPath(){
    if [[ "$PATH" != *"$1"*  ]]; then
        export PATH="$PATH:$1"
    fi
}

addToPathFront(){
    if [[ "$PATH" != *"$1"*  ]]; then
        export PATH="$1:$PATH"
    fi
}


recordingScreen() {
    tmux new-session -s recording -d rec_screen
    clear
}

recordingStop() {
    tmux send-keys -t recording:1 C-c
    nautilus $HOME/Videos &
    clear
}


set_rand_wallpaper(){
    find ~/github/mmngreco/wallpapers \
        -type f \
        -not -name "README.md" \
        -not -path "*/.git/*" \
        | shuf -n1\
        | xargs -L1 -I IMG hsetroot -fill IMG
}



pip-lastest() {
    pip install $1==kk |& grep -oP '.*\b\K\d+\.\d+\.\d+\b'
}


ipytdd ()  {
    ipython
    echo "Restarting ipython, press a key to abort."
    read -t 1 cancel
    if [ -z "$cancel" ]
    then
        ipytdd
    fi
}


conda-here () {
    # conda-here [prefix] [*conda-args]
    local prefix="${1:-$PWD/.venv/$(echo $pyver | tr -d = | tr -d .)}"
    local pyver="python=3.7"

    if [ $# -eq 0 ]; then
        conda create --prefix $prefix $pyver pip -y
    else
        conda create --prefix $prefix ${@:2}
    fi

    conda activate "$(abspath $prefix)"

    if [ ! -f ./$AUTOENV_ENV_FILENAME ]; then
        echo conda activate \""$(abspath $prefix)"\" >> $AUTOENV_ENV_FILENAME
        echo $AUTOENV_ENV_FILENAME >> .gitignore
    fi
}


conda-activate() {
    local prefix="$PWD/.venv"
    local selected=$(find $prefix -maxdepth 1 -mindepth 1 -type d | fzf --select-1 --ansi -q "$1" --height 10%)
    conda activate $selected
}

# =============================================================================
# Docker

dfix() {
    # see https://serverfault.com/a/642984/573706
    # sudo apt-get install bridge-utils
    sudo pkill docker
    sudo iptables -t nat -F
    sudo ifconfig docker0 down
    sudo brctl delbr docker0
    sudo service docker restart
}


drun() {

    DIR=$PWD
    IMAGE_NAME=${1:-mmngreco/dev:0.3.2}
    echo Container name:
    echo $CONTAINER_NAME

    docker run \
        --env "DOTFILES=/root/.dotfiles" \
        --volume "$HOME/.ssh:/root/.ssh" \
        --volume "$DIR:/root/$(basename $DIR)" \
        --volume "$HOME/.dotfiles:/root/.dotfiles" \
        --volume "$HOME/.dotfiles/shell/bashrc:/root/.bashrc" \
        --workdir "/root/$(basename $DIR)" \
        --name "$CONTAINER_NAME" \
        --interactive \
        --tty \
        "$IMAGE_NAME" \
        $2
}


ddev() {

    DIR=$PWD
    IMAGE_NAME=${1:-$DEFAULT_IMG}
    SUFFIX="${2:-dev}"
    CONTAINER_NAME="$(basename $DIR)-$(echo $SUFFIX | tr -d .)"

    if [ "$(docker ps -a -q -f name=$CONTAINER_NAME)" ]
    then
        echo "Attaching the container $CONTAINER_NAME"
        docker stop $CONTAINER_NAME
        docker start -ia $CONTAINER_NAME
    else
        echo "Creating the container..."
        docker run \
            --env TERM="xterm-256color" \
            --volume "$HOME/.ssh:/root/.ssh" \
            --volume "$DIR:/git/$(basename $DIR)" \
            --workdir "/git/$(basename $DIR)" \
            --name "$CONTAINER_NAME" \
            --interactive \
            --tty \
            "$IMAGE_NAME"
    fi

}


dclean() {
    docker system prune -a -f
    sudo systemctl stop docker
    sudo systemctl stop docker.socket
    sudo rm -rf /var/lib/docker
    sudo systemctl start docker.socket
    sudo systemctl start docker

}

chown-here () {
    sudo chown -R $USERNAME:$USERNAME ./
}

selectProjectFzf () {
    # Print out the abslute path of every project (which has .git) at HOME dir.
    # query="${1:-tesser}"
    query="${1}"
    listProjects | fzf --select-1 --ansi -q "$query" --height 10% -m --bind "space:toggle"
}


newProject () {
    # find projects using .git folder as reference
    dir=$(listProjectContainers | fzf --select-1 --height 10%)
    prj=$1
    if [ -z $prj ]; then
        echo "Enter project name: "
        read prj
    fi
    mkdir $dir/$prj
    cd $dir/$prj
}

fzfProjects () {
    # Print out the abslute path of every project (which has .git) at HOME dir.
    # query="${1:-tesser}"
    selectProjectFzf $@
}

cdProjects () {
    # Change directory to a project using fzf
    cd $(fzfProjects $@)
}

nvp () {
    # neovim project
    query="${1}"
    fzfProjects $query | xargs -I DIR bash -c "pushd DIR > /dev/null && nvim DIR && popd > /dev/null"
}


txw() {

    if [[ -z "$@" ]]
    then
        # no arguments
        folder_query="${1}"
        selectProjectFzf $folder_query \
            | xargs -L1 -I FOLDER bash -c "tmux new-window -c FOLDER"
    else
        # when arguments are passed
        for folder_query in $@
        do
            selectProjectFzf $folder_query \
                | xargs -L1 -I FOLDER bash -c "tmux new-window -c FOLDER"
        done
    fi
}


# txs() {
#     case $1 in
#         com)
#             tmux new-session -d -s com -c ~/gitlab/COM
#             tmux send-keys -t com "txw $2 && clear" Enter
#             tmux attach -t com
#             ;;
#         vpn)
#             tmux new-session -d -s vpn
#             tmux send-keys -t vpn "ets-vpn" Enter
#             ;;
#         gitlab)
#             tmux new-session -d -s "gitlab" -c ~/gitlab
#             tmux send-keys -t gitlab "txw $2 && clear" Enter
#             tmux attach -t gitlab
#             ;;
#         github)
#             tmux new-session -d -s "github" -c ~/github
#             tmux send-keys "txw $2 && clear" Enter
#             tmux attach -t github
#             ;;
#         cancel)
#             ;;
#         *)
#             tmux-sessionizer $1
#             ;;
#     esac
# }
#

# =============================================================================
# cheat sheet
# cs () {
#     # cheat sheet
#     url="$(echo cht.sh/$@ | tr ' ' '+')"
#     echo $url
#     curl -s $url
# }

csl () {
    # cheat sheet pipe less
    cs $@ | less
}

function extract_and_remove {
  extract $1
  rm -f $1
}

# function abspath() {
#     if [ -d "$1" ]; then
#         echo "$(cd $1; pwd)"
#     elif [ -f "$1" ]; then
#         if [[ $1 == */* ]]; then
#             echo "$(cd ${1%/*}; pwd)/${1##*/}"
#         else
#             echo "$(pwd)/$1"
#         fi
#     fi
# }
#

function gi() { curl -L -s https://www.gitignore.io/api/$@ ;}


# nq() { d=$(basename "$PWD"); nd=$(printf "../ex%02d*/" $((${d:2:2}+1))); cd $nd ; }

# to go to directory of previous question
# pq() { d=$(basename "$PWD"); pd=$(printf "../ex%02d*/" $((${d:2:2}-1))); cd $pd ; }

# =============================================================================
# Git

is_in_git_repo() {
  git rev-parse HEAD > /dev/null 2>&1
}

_gf() {
  # Selects git file
  is_in_git_repo &&
    git -c color.status=always status --short |
    fzf --height 40% -m --ansi --nth 2..,.. | awk '{print $2}'
}

_gb() {
  # Selects git branch
  is_in_git_repo &&
    git branch -a -vv --color=always | grep -v '/HEAD\s' |
    fzf --height 40% --ansi --multi --tac | sed 's/^..//' | awk '{print $1}' |
    sed 's#^remotes/[^/]*/##'
}

_gt() {
  # Selects git tag
  is_in_git_repo &&
    git tag --sort -version:refname |
    fzf --height 40% --multi
}

_gh() {
  # Select git commit from the history
  is_in_git_repo &&
    git log --date=short --format="%C(green)%C(bold)%cd %C(auto)%h%d %s (%an)" --graph |
    fzf --height 40% --ansi --no-sort --reverse --multi | grep -o '[a-f0-9]\{7,\}'
}

_gr() {
  # Select git remotes
  is_in_git_repo &&
    git remote -v | awk '{print $1 " " $2}' | uniq |
    fzf --height 40% --tac | awk '{print $1}'
}

parse_git_branch () {
    git name-rev HEAD 2> /dev/null | sed 's#HEAD\ \(.*\)# [git:\1]#'
}

parse_svn_branch() {
    parse_svn_url | sed -e 's#^'"$(parse_svn_repository_root)"'##g' | awk -F / '{print " [svn:" $2 "]"}'
}

parse_svn_url() {
    svn info 2>/dev/null | sed -ne 's#^URL: ##p'
}

parse_svn_repository_root() {
    svn info 2>/dev/null | grep -e '^Repository Root:*' | sed -e 's#^Repository Root: *\(.*\)#\1\/#g '
    #svn info 2>/dev/null | sed -ne 's#^Repository Root: ##p'
}

pyright-config-here() {
    cp $DOTFILES/python/pyrightconfig.json .
}

pip-dev-tools() {
    pip install -r $DOTFILES/python/requirements-dev.txt
}

todo() {
    TODO_DEFAULT=${TODO_DEFAULT:-~/MyTODO.md}
    TODO_FILE=${1:-TODO.md}
    [[ -f $TODO_FILE ]] && nvim $TODO_FILE || nvim $TODO_DEFAULT
}


pdbrc-here () {
    echo "# b $PWD/src/file.py:lineno, condition" > .pdbrc
}


function jenkinsLint () {
    # https://www.jenkins.io/doc/book/pipeline/development/
    jfile=${1:-Jenkinsfile}
    curl --user "${JENKINS_USER_ID}:${JENKINS_API_TOKEN}" -X POST -F "jenkinsfile=<${jfile}" "${JENKINS_URL}/pipeline-model-converter/validate"
}


function gcloud_bucket_project() {
	BUCKET_NAME=$1
	PROJECT_NUMBER=$(curl -X GET \
	-H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
	"https://storage.googleapis.com/storage/v1/b/${BUCKET_NAME}?fields=projectNumber" | jq .projectNumber | sed 's/"//' | sed 's/"//')
	gcloud projects list --filter "PROJECT_NUMBER=${PROJECT_NUMBER}"
}

