#!/usr/bin/env bash

# nnn config
export NNN_FIFO=/tmp/nnn.fifo
# export NNN_OPENER=nuke
export NNN_PLUG='f:finder;o:fzopen;p:mocq;d:diffs;t:nmount;v:imgview'
alias lsn='nnn -de'

nnn_cd()
{
    if ! [ -z "$NNN_PIPE" ]; then
        printf "%s\0" "0c${PWD}" > "${NNN_PIPE}" !&
    fi
}

trap nnn_cd EXIT
